
console.log('initMapFile');
function divideRegion(regData, regName) {
	console.log('initFunction');
	console.log(regData);
	console.log(regData.preSchool);
	placemarks[regName] = {};
	console.log(placemarks);
	Object.keys(schoolType).map(key => schoolType[key]).forEach(type => {
		placemarks[regName][type] = [];
		if (regData[type]) {
			
			regData[type].forEach(el => {
				console.log('longitude');
				console.log(el);
				console.log(el.Longitude);
				auxPlacemark = new ymaps.Placemark([el.Longitude, el.Latitude],
					{
						hintContent: el.Name,
						balloonContent: `<a href="${el.WebLink}" target="_blank">${el.Name}</a>`
					}, {
					iconLayout: 'default#image',
					iconImageHref: 'icons/logo.png',
					iconImageSize: [30, 30],
					iconImageOffset: [-5, -38],
					visible: false,
				}
				);
				placemarks[regName][type].push(auxPlacemark);
				map.geoObjects.add(auxPlacemark);
			});
		}
	});
	//placemarks[regName][type].push(regData[type]);
	// new ymaps.Placemark([regData.Longitude, regData.Latitude],
	// 	{
	// 		hintContent: regData.Name,
	// 		balloonContent: `<a href="${regData.WebLink}" target="_blank">${regData.Name}</a>`
	// 	}, {
	// 	iconLayout: 'default#image',
	// 	iconImageHref: 'icons/logo.png',
	// 	iconImageSize: [30, 30],
	// 	iconImageOffset: [-5, -38]
	// });
}

function initMap() {
	console.log('init');
	ymaps.ready(function () {

		map = new ymaps.Map("map", {
			center: [27.525773, 53.89079],
			zoom: 8,
			controls: ['zoomControl', 'typeSelector']
		});

		map.setCenter(
			[27.525773, 53.89079],
			8,
			{ duration: 400 }
		);

		// Создадим элемент управления поиск
		var searchControl = new ymaps.control.SearchControl({
			options: {
				provider: 'yandex#search'
			}
		});

		// Добавим поиск на карту
		map.controls.add(searchControl);

		map.controls.add(listBox, { float: 'left' });
		//Инициализация районов --> 
		map.geoObjects.add(berezinskiy);
		// console.log(berezinskiyPlaceMarks);
		// //map.geoObjects.add(berezinskiyPlaceMarks[0]);
		// berezinskiyPlaceMarks['preSchool'].forEach(element => {
		// 	map.geoObjects.add(element);
		// });


		Object.keys(regionName).map(key => regionName[key]).forEach(regName => {
			console.log('obj keys');
			console.log(data);
			console.log(regName);
			divideRegion(data[regName], regName);
		});
		console.log('here it is');
		console.log(placemarks);
		// map.geoObjects.add(borisovskiy);
		// map.geoObjects.add(vileyskiy);
		// map.geoObjects.add(volozhinskiy);
		// map.geoObjects.add(dzerzhinskiy);
		// map.geoObjects.add(kletskiy);
		// map.geoObjects.add(kopilskiy);
		// map.geoObjects.add(krupski);
		// map.geoObjects.add(logoyski);
		// map.geoObjects.add(lubanski);
		// map.geoObjects.add(minskiy);
		// map.geoObjects.add(molodzechnenskiy);
		// map.geoObjects.add(myadzelskiy);
		// map.geoObjects.add(nesvizhskiy);
		// map.geoObjects.add(pukhovichskiy);
		// map.geoObjects.add(slutskiy);
		// map.geoObjects.add(smolevichskiy);
		// map.geoObjects.add(soligorskiy);
		// map.geoObjects.add(starodorozhskiy);
		// map.geoObjects.add(stolbcovskiy);
		// map.geoObjects.add(uzdenskiy);
		// map.geoObjects.add(chervenskiy);
		// map.geoObjects.add(jodino);
		// map.geoObjects.add(minsk);
		// map.geoObjects.add(jodinoPlacemark1);
		// map.geoObjects.add(jodinoPlacemark2);
		// map.geoObjects.add(jodinoPlacemark3);
		// map.geoObjects.add(jodinoPlacemark4);
		// map.geoObjects.add(jodinoPlacemark5);
		// map.geoObjects.add(jodinoPlacemark6);
		// map.geoObjects.add(jodinoPlacemark7);
		// map.geoObjects.add(jodinoPlacemark8);
		// map.geoObjects.add(jodinoPlacemark9);
		// map.geoObjects.add(jodinoPlacemark10);
		// map.geoObjects.add(jodinoPlacemark11);
		// map.geoObjects.add(jodinoPlacemark12);
		// map.geoObjects.add(jodinoPlacemark13);
		// map.geoObjects.add(jodinoPlacemark14);
		// map.geoObjects.add(jodinoPlacemark15);
		// map.geoObjects.add(borisovskyPlacemark1);
		// map.geoObjects.add(borisovskyPlacemark2);
		// map.geoObjects.add(borisovskyPlacemark3);
		// map.geoObjects.add(borisovskyPlacemark4);
		// map.geoObjects.add(borisovskyPlacemark5);
		// map.geoObjects.add(borisovskyPlacemark6);
		// map.geoObjects.add(borisovskyPlacemark7);
		// map.geoObjects.add(borisovskyPlacemark8);
		// map.geoObjects.add(borisovskyPlacemark9);
		// map.geoObjects.add(borisovskyPlacemark10);
		// map.geoObjects.add(borisovskyPlacemark11);
		// map.geoObjects.add(borisovskyPlacemark12);
		// map.geoObjects.add(borisovskyPlacemark13);
		// map.geoObjects.add(borisovskyPlacemark14);
		// map.geoObjects.add(borisovskyPlacemark15);
		// map.geoObjects.add(borisovskyPlacemark16);
		// map.geoObjects.add(borisovskyPlacemark17);
		// map.geoObjects.add(borisovskyPlacemark18);
		// map.geoObjects.add(borisovskyPlacemark19);
		// map.geoObjects.add(borisovskyPlacemark20);
		// map.geoObjects.add(borisovskyPlacemark21);
		// map.geoObjects.add(borisovskyPlacemark22);
		// map.geoObjects.add(borisovskyPlacemark23);
		// map.geoObjects.add(borisovskyPlacemark24);
		// map.geoObjects.add(borisovskyPlacemark25);
		// map.geoObjects.add(borisovskyPlacemark26);
		// map.geoObjects.add(borisovskyPlacemark27);
		// map.geoObjects.add(borisovskyPlacemark28);
		// map.geoObjects.add(borisovskyPlacemark29);
		// map.geoObjects.add(borisovskyPlacemark30);
		// map.geoObjects.add(borisovskyPlacemark31);
		// map.geoObjects.add(borisovskyPlacemark32);
		// map.geoObjects.add(borisovskyPlacemark33);
		// map.geoObjects.add(borisovskyPlacemark34);
		// map.geoObjects.add(borisovskyPlacemark35);
		// map.geoObjects.add(borisovskyPlacemark36);
		// map.geoObjects.add(borisovskyPlacemark37);
		// map.geoObjects.add(borisovskyPlacemark38);
		// map.geoObjects.add(borisovskyPlacemark39);
		// map.geoObjects.add(borisovskyPlacemark40);
		// map.geoObjects.add(borisovskyPlacemark41);
		// map.geoObjects.add(borisovskyPlacemark42);
		// map.geoObjects.add(borisovskyPlacemark43);
		// map.geoObjects.add(borisovskyPlacemark44);
		// map.geoObjects.add(borisovskyPlacemark45);
		// map.geoObjects.add(borisovskyPlacemark46);
		// map.geoObjects.add(borisovskyPlacemark47);
		// map.geoObjects.add(borisovskyPlacemark48);
		// map.geoObjects.add(borisovskyPlacemark49);
		// map.geoObjects.add(borisovskyPlacemark50);
		// map.geoObjects.add(borisovskyPlacemark51);
		// map.geoObjects.add(borisovskyPlacemark52);
		// map.geoObjects.add(borisovskyPlacemark53);
		// map.geoObjects.add(borisovskyPlacemark54);
		// map.geoObjects.add(borisovskyPlacemark55);
		// map.geoObjects.add(borisovskyPlacemark56);
		// map.geoObjects.add(borisovskyPlacemark57);
		// map.geoObjects.add(borisovskyPlacemark571);
		// map.geoObjects.add(borisovskyPlacemark58);
		// map.geoObjects.add(borisovskyPlacemark59);
		// map.geoObjects.add(borisovskyPlacemark60);
		// map.geoObjects.add(borisovskyPlacemark61);
		// map.geoObjects.add(vileyskiyPlacemark1);
		// map.geoObjects.add(vileyskiyPlacemark2);
		// map.geoObjects.add(vileyskiyPlacemark3);
		// map.geoObjects.add(vileyskiyPlacemark4);
		// map.geoObjects.add(vileyskiyPlacemark5);
		// map.geoObjects.add(vileyskiyPlacemark6);
		// map.geoObjects.add(vileyskiyPlacemark7);
		// map.geoObjects.add(vileyskiyPlacemark8);
		// map.geoObjects.add(vileyskiyPlacemark9);
		// map.geoObjects.add(vileyskiyPlacemark10);
		// map.geoObjects.add(vileyskiyPlacemark11);
		// map.geoObjects.add(vileyskiyPlacemark12);
		// map.geoObjects.add(vileyskiyPlacemark13);
		// map.geoObjects.add(vileyskiyPlacemark14);
		// map.geoObjects.add(vileyskiyPlacemark15);
		// map.geoObjects.add(vileyskiyPlacemark16);
		// map.geoObjects.add(vileyskiyPlacemark18);
		// map.geoObjects.add(vileyskiyPlacemark20);
		// map.geoObjects.add(vileyskiyPlacemark21);
		// map.geoObjects.add(vileyskiyPlacemark22);
		// map.geoObjects.add(vileyskiyPlacemark23);
		// map.geoObjects.add(vileyskiyPlacemark24);
		// map.geoObjects.add(vileyskiyPlacemark25);
		// map.geoObjects.add(vileyskiyPlacemark26);
		// map.geoObjects.add(vileyskiyPlacemark27);
		// map.geoObjects.add(volozhinskiyPlacemark1);
		// map.geoObjects.add(volozhinskiyPlacemark2);
		// map.geoObjects.add(volozhinskiyPlacemark3);
		// map.geoObjects.add(volozhinskiyPlacemark4);
		// map.geoObjects.add(volozhinskiyPlacemark5);
		// map.geoObjects.add(volozhinskiyPlacemark6);
		// map.geoObjects.add(volozhinskiyPlacemark7);
		// map.geoObjects.add(volozhinskiyPlacemark8);
		// map.geoObjects.add(volozhinskiyPlacemark9);
		// map.geoObjects.add(volozhinskiyPlacemark10);
		// map.geoObjects.add(volozhinskiyPlacemark11);
		// map.geoObjects.add(volozhinskiyPlacemark12);
		// map.geoObjects.add(volozhinskiyPlacemark13);
		// map.geoObjects.add(volozhinskiyPlacemark14);
		// map.geoObjects.add(volozhinskiyPlacemark15);
		// map.geoObjects.add(volozhinskiyPlacemark16);
		// map.geoObjects.add(volozhinskiyPlacemark17);
		// map.geoObjects.add(dzerzhinskiyPlacemark1);
		// map.geoObjects.add(dzerzhinskiyPlacemark2);
		// map.geoObjects.add(dzerzhinskiyPlacemark3);
		// map.geoObjects.add(dzerzhinskiyPlacemark4);
		// map.geoObjects.add(dzerzhinskiyPlacemark5);
		// map.geoObjects.add(dzerzhinskiyPlacemark6);
		// map.geoObjects.add(dzerzhinskiyPlacemark7);
		// map.geoObjects.add(dzerzhinskiyPlacemark8);
		// map.geoObjects.add(dzerzhinskiyPlacemark9);
		// map.geoObjects.add(dzerzhinskiyPlacemark10);
		// map.geoObjects.add(dzerzhinskiyPlacemark11);
		// map.geoObjects.add(dzerzhinskiyPlacemark12);
		// map.geoObjects.add(dzerzhinskiyPlacemark13);
		// map.geoObjects.add(dzerzhinskiyPlacemark14);
		// map.geoObjects.add(dzerzhinskiyPlacemark15);
		// map.geoObjects.add(dzerzhinskiyPlacemark16);
		// map.geoObjects.add(dzerzhinskiyPlacemark17);
		// map.geoObjects.add(dzerzhinskiyPlacemark18);
		// map.geoObjects.add(dzerzhinskiyPlacemark19);
		// map.geoObjects.add(dzerzhinskiyPlacemark20);
		// map.geoObjects.add(dzerzhinskiyPlacemark21);
		// map.geoObjects.add(dzerzhinskiyPlacemark22);
		// map.geoObjects.add(dzerzhinskiyPlacemark23);
		// map.geoObjects.add(dzerzhinskiyPlacemark24);
		// map.geoObjects.add(dzerzhinskiyPlacemark25);
		// map.geoObjects.add(dzerzhinskiyPlacemark26);
		// map.geoObjects.add(dzerzhinskiyPlacemark27);
		// map.geoObjects.add(dzerzhinskiyPlacemark28);
		// map.geoObjects.add(dzerzhinskiyPlacemark29);
		// map.geoObjects.add(dzerzhinskiyPlacemark30);
		// map.geoObjects.add(dzerzhinskiyPlacemark31);
		// map.geoObjects.add(kletskiyPlacemark1);
		// map.geoObjects.add(kletskiyPlacemark2);
		// map.geoObjects.add(kletskiyPlacemark3);
		// map.geoObjects.add(kletskiyPlacemark4);
		// map.geoObjects.add(kletskiyPlacemark5);
		// map.geoObjects.add(kletskiyPlacemark6);
		// map.geoObjects.add(kletskiyPlacemark7);
		// map.geoObjects.add(kletskiyPlacemark10);
		// map.geoObjects.add(kletskiyPlacemark11);
		// map.geoObjects.add(kletskiyPlacemark12);
		// map.geoObjects.add(kletskiyPlacemark14);
		// map.geoObjects.add(kletskiyPlacemark15);
		// map.geoObjects.add(kletskiyPlacemark16);
		// map.geoObjects.add(kletskiyPlacemark17);
		// map.geoObjects.add(kletskiyPlacemark18);
		// map.geoObjects.add(kopilskiyPlacemark1);
		// map.geoObjects.add(kopilskiyPlacemark2);
		// map.geoObjects.add(kopilskiyPlacemark3);
		// map.geoObjects.add(kopilskiyPlacemark4);
		// map.geoObjects.add(kopilskiyPlacemark5);
		// map.geoObjects.add(kopilskiyPlacemark6);
		// map.geoObjects.add(kopilskiyPlacemark7);
		// map.geoObjects.add(kopilskiyPlacemark8);
		// map.geoObjects.add(kopilskiyPlacemark9);
		// map.geoObjects.add(kopilskiyPlacemark11);
		// map.geoObjects.add(kopilskiyPlacemark12);
		// map.geoObjects.add(kopilskiyPlacemark13);
		// map.geoObjects.add(kopilskiyPlacemark14);
		// map.geoObjects.add(kopilskiyPlacemark15);
		// map.geoObjects.add(kopilskiyPlacemark16);
		// map.geoObjects.add(kopilskiyPlacemark17);
		// map.geoObjects.add(kopilskiyPlacemark18);
		// map.geoObjects.add(kopilskiyPlacemark19);
		// map.geoObjects.add(kopilskiyPlacemark20);
		// map.geoObjects.add(kopilskiyPlacemark21);
		// map.geoObjects.add(kopilskiyPlacemark22);
		// map.geoObjects.add(kopilskiyPlacemark23);
		// map.geoObjects.add(kopilskiyPlacemark24);
		// map.geoObjects.add(kopilskiyPlacemark25);
		// map.geoObjects.add(krupskiPlacemark1);
		// map.geoObjects.add(krupskiPlacemark2);
		// map.geoObjects.add(krupskiPlacemark3);
		// map.geoObjects.add(krupskiPlacemark4);
		// map.geoObjects.add(krupskiPlacemark5);
		// map.geoObjects.add(krupskiPlacemark6);
		// map.geoObjects.add(krupskiPlacemark7);
		// map.geoObjects.add(krupskiPlacemark8);
		// map.geoObjects.add(krupskiPlacemark9);
		// map.geoObjects.add(krupskiPlacemark10);
		// map.geoObjects.add(krupskiPlacemark11);
		// map.geoObjects.add(krupskiPlacemark12);
		// map.geoObjects.add(krupskiPlacemark13);
		// map.geoObjects.add(logoyskiPlacemark1);
		// map.geoObjects.add(logoyskiPlacemark2);
		// map.geoObjects.add(logoyskiPlacemark3);
		// map.geoObjects.add(logoyskiPlacemark4);
		// map.geoObjects.add(logoyskiPlacemark5);
		// map.geoObjects.add(logoyskiPlacemark6);
		// map.geoObjects.add(logoyskiPlacemark7);
		// map.geoObjects.add(logoyskiPlacemark9);
		// map.geoObjects.add(logoyskiPlacemark10);
		// map.geoObjects.add(logoyskiPlacemark11);
		// map.geoObjects.add(logoyskiPlacemark12);
		// map.geoObjects.add(logoyskiPlacemark13);
		// map.geoObjects.add(logoyskiPlacemark14);
		// map.geoObjects.add(logoyskiPlacemark15);
		// map.geoObjects.add(logoyskiPlacemark16);
		// map.geoObjects.add(logoyskiPlacemark17);
		// map.geoObjects.add(logoyskiPlacemark18);
		// map.geoObjects.add(logoyskiPlacemark19);
		// map.geoObjects.add(logoyskiPlacemark20);
		// map.geoObjects.add(logoyskiPlacemark21);
		// map.geoObjects.add(logoyskiPlacemark22);
		// map.geoObjects.add(logoyskiPlacemark23);
		// map.geoObjects.add(logoyskiPlacemark24);
		// map.geoObjects.add(logoyskiPlacemark25);
		// map.geoObjects.add(lubanskiPlacemark1);
		// map.geoObjects.add(lubanskiPlacemark2);
		// map.geoObjects.add(lubanskiPlacemark3);
		// map.geoObjects.add(lubanskiPlacemark4);
		// map.geoObjects.add(lubanskiPlacemark5);
		// map.geoObjects.add(lubanskiPlacemark6);
		// map.geoObjects.add(lubanskiPlacemark7);
		// map.geoObjects.add(lubanskiPlacemark8);
		// map.geoObjects.add(lubanskiPlacemark9);
		// map.geoObjects.add(lubanskiPlacemark10);
		// map.geoObjects.add(lubanskiPlacemark11);
		// map.geoObjects.add(lubanskiPlacemark12);
		// map.geoObjects.add(lubanskiPlacemark13);
		// map.geoObjects.add(lubanskiPlacemark14);
		// map.geoObjects.add(lubanskiPlacemark15);
		// map.geoObjects.add(lubanskiPlacemark16);
		// map.geoObjects.add(lubanskiPlacemark17);
		// map.geoObjects.add(lubanskiPlacemark18);
		// map.geoObjects.add(lubanskiPlacemark19);
		// map.geoObjects.add(lubanskiPlacemark20);
		// map.geoObjects.add(lubanskiPlacemark21);
		// map.geoObjects.add(lubanskiPlacemark22);
		// map.geoObjects.add(lubanskiPlacemark23);
		// map.geoObjects.add(lubanskiPlacemark24);
		// map.geoObjects.add(minskiyPlacemark1);
		// map.geoObjects.add(minskiyPlacemark2);
		// map.geoObjects.add(minskiyPlacemark3);
		// map.geoObjects.add(minskiyPlacemark4);
		// map.geoObjects.add(minskiyPlacemark5);
		// map.geoObjects.add(minskiyPlacemark6);
		// map.geoObjects.add(minskiyPlacemark7);
		// map.geoObjects.add(minskiyPlacemark8);
		// map.geoObjects.add(minskiyPlacemark9);
		// map.geoObjects.add(minskiyPlacemark10);
		// map.geoObjects.add(minskiyPlacemark11);
		// map.geoObjects.add(minskiyPlacemark12);
		// map.geoObjects.add(minskiyPlacemark13);
		// map.geoObjects.add(minskiyPlacemark14);
		// map.geoObjects.add(minskiyPlacemark15);
		// map.geoObjects.add(minskiyPlacemark16);
		// map.geoObjects.add(minskiyPlacemark17);
		// map.geoObjects.add(minskiyPlacemark18);
		// map.geoObjects.add(minskiyPlacemark19);
		// map.geoObjects.add(minskiyPlacemark20);
		// map.geoObjects.add(minskiyPlacemark21);
		// map.geoObjects.add(minskiyPlacemark22);
		// map.geoObjects.add(minskiyPlacemark23);
		// map.geoObjects.add(minskiyPlacemark24);
		// map.geoObjects.add(minskiyPlacemark25);
		// map.geoObjects.add(minskiyPlacemark26);
		// map.geoObjects.add(minskiyPlacemark27);
		// map.geoObjects.add(minskiyPlacemark28);
		// map.geoObjects.add(minskiyPlacemark29);
		// map.geoObjects.add(minskiyPlacemark30);
		// map.geoObjects.add(minskiyPlacemark31);
		// map.geoObjects.add(minskiyPlacemark32);
		// map.geoObjects.add(minskiyPlacemark33);
		// map.geoObjects.add(minskiyPlacemark34);
		// map.geoObjects.add(minskiyPlacemark35);
		// map.geoObjects.add(minskiyPlacemark36);
		// map.geoObjects.add(minskiyPlacemark37);
		// map.geoObjects.add(minskiyPlacemark38);
		// map.geoObjects.add(minskiyPlacemark39);
		// map.geoObjects.add(minskiyPlacemark40);
		// map.geoObjects.add(minskiyPlacemark41);
		// map.geoObjects.add(minskiyPlacemark42);
		// map.geoObjects.add(minskiyPlacemark43);
		// map.geoObjects.add(minskiyPlacemark44);
		// map.geoObjects.add(minskiyPlacemark45);
		// map.geoObjects.add(minskiyPlacemark46);
		// map.geoObjects.add(minskiyPlacemark47);
		// map.geoObjects.add(minskiyPlacemark48);
		// map.geoObjects.add(minskiyPlacemark49);
		// map.geoObjects.add(minskiyPlacemark50);
		// map.geoObjects.add(minskiyPlacemark51);
		// map.geoObjects.add(minskiyPlacemark52);
		// map.geoObjects.add(minskiyPlacemark53);
		// map.geoObjects.add(minskiyPlacemark54);
		// map.geoObjects.add(minskiyPlacemark55);
		// map.geoObjects.add(minskiyPlacemark56);
		// map.geoObjects.add(minskiyPlacemark57);
		// map.geoObjects.add(minskiyPlacemark58);
		// map.geoObjects.add(minskiyPlacemark59);
		// map.geoObjects.add(minskiyPlacemark60);
		// map.geoObjects.add(minskiyPlacemark61);
		// map.geoObjects.add(minskiyPlacemark62);
		// map.geoObjects.add(minskiyPlacemark63);
		// map.geoObjects.add(minskiyPlacemark64);
		// map.geoObjects.add(minskiyPlacemark65);
		// map.geoObjects.add(minskiyPlacemark66);
		// map.geoObjects.add(minskiyPlacemark67);
		// map.geoObjects.add(minskiyPlacemark68);
		// map.geoObjects.add(minskiyPlacemark69);
		// map.geoObjects.add(molodzechnenskiyPlacemark1);
		// map.geoObjects.add(molodzechnenskiyPlacemark2);
		// map.geoObjects.add(molodzechnenskiyPlacemark3);
		// map.geoObjects.add(molodzechnenskiyPlacemark4);
		// map.geoObjects.add(molodzechnenskiyPlacemark5);
		// map.geoObjects.add(molodzechnenskiyPlacemark6);
		// map.geoObjects.add(molodzechnenskiyPlacemark7);
		// map.geoObjects.add(molodzechnenskiyPlacemark8);
		// map.geoObjects.add(molodzechnenskiyPlacemark9);
		// map.geoObjects.add(molodzechnenskiyPlacemark10);
		// map.geoObjects.add(molodzechnenskiyPlacemark11);
		// map.geoObjects.add(molodzechnenskiyPlacemark12);
		// map.geoObjects.add(molodzechnenskiyPlacemark13);
		// map.geoObjects.add(molodzechnenskiyPlacemark14);
		// map.geoObjects.add(molodzechnenskiyPlacemark15);
		// map.geoObjects.add(molodzechnenskiyPlacemark16);
		// map.geoObjects.add(molodzechnenskiyPlacemark17);
		// map.geoObjects.add(molodzechnenskiyPlacemark18);
		// map.geoObjects.add(molodzechnenskiyPlacemark19);
		// map.geoObjects.add(molodzechnenskiyPlacemark20);
		// map.geoObjects.add(molodzechnenskiyPlacemark21);
		// map.geoObjects.add(molodzechnenskiyPlacemark22);
		// map.geoObjects.add(molodzechnenskiyPlacemark23);
		// map.geoObjects.add(molodzechnenskiyPlacemark24);
		// map.geoObjects.add(molodzechnenskiyPlacemark25);
		// map.geoObjects.add(molodzechnenskiyPlacemark26);
		// map.geoObjects.add(molodzechnenskiyPlacemark27);
		// map.geoObjects.add(molodzechnenskiyPlacemark28);
		// map.geoObjects.add(molodzechnenskiyPlacemark29);
		// map.geoObjects.add(molodzechnenskiyPlacemark30);
		// map.geoObjects.add(molodzechnenskiyPlacemark31);
		// map.geoObjects.add(molodzechnenskiyPlacemark32);
		// map.geoObjects.add(molodzechnenskiyPlacemark33);
		// map.geoObjects.add(molodzechnenskiyPlacemark34);
		// map.geoObjects.add(molodzechnenskiyPlacemark35);
		// map.geoObjects.add(molodzechnenskiyPlacemark36);
		// map.geoObjects.add(molodzechnenskiyPlacemark37);
		// map.geoObjects.add(molodzechnenskiyPlacemark38);
		// map.geoObjects.add(molodzechnenskiyPlacemark39);
		// map.geoObjects.add(molodzechnenskiyPlacemark40);
		// map.geoObjects.add(molodzechnenskiyPlacemark41);
		// map.geoObjects.add(molodzechnenskiyPlacemark42);
		// map.geoObjects.add(molodzechnenskiyPlacemark43);
		// map.geoObjects.add(molodzechnenskiyPlacemark44);
		// map.geoObjects.add(molodzechnenskiyPlacemark45);
		// map.geoObjects.add(molodzechnenskiyPlacemark46);
		// map.geoObjects.add(molodzechnenskiyPlacemark47);
		// map.geoObjects.add(molodzechnenskiyPlacemark48);
		// map.geoObjects.add(molodzechnenskiyPlacemark49);
		// map.geoObjects.add(molodzechnenskiyPlacemark50);
		// map.geoObjects.add(molodzechnenskiyPlacemark51);
		// map.geoObjects.add(molodzechnenskiyPlacemark52);
		// map.geoObjects.add(molodzechnenskiyPlacemark53);
		// map.geoObjects.add(molodzechnenskiyPlacemark54);
		// map.geoObjects.add(molodzechnenskiyPlacemark55);
		// map.geoObjects.add(myadzelskiyPlacemark1);
		// map.geoObjects.add(myadzelskiyPlacemark2);
		// map.geoObjects.add(myadzelskiyPlacemark3);
		// map.geoObjects.add(myadzelskiyPlacemark4);
		// map.geoObjects.add(myadzelskiyPlacemark5);
		// map.geoObjects.add(myadzelskiyPlacemark6);
		// map.geoObjects.add(myadzelskiyPlacemark7);
		// map.geoObjects.add(myadzelskiyPlacemark8);
		// map.geoObjects.add(myadzelskiyPlacemark9);
		// map.geoObjects.add(myadzelskiyPlacemark10);
		// map.geoObjects.add(myadzelskiyPlacemark11);
		// map.geoObjects.add(myadzelskiyPlacemark12);
		// map.geoObjects.add(myadzelskiyPlacemark13);
		// map.geoObjects.add(myadzelskiyPlacemark14);
		// map.geoObjects.add(soligorskiyPlacemark1);
		// map.geoObjects.add(soligorskiyPlacemark2);
		// map.geoObjects.add(soligorskiyPlacemark3);
		// map.geoObjects.add(soligorskiyPlacemark4);
		// map.geoObjects.add(soligorskiyPlacemark5);
		// map.geoObjects.add(soligorskiyPlacemark6);
		// map.geoObjects.add(soligorskiyPlacemark7);
		// map.geoObjects.add(soligorskiyPlacemark8);
		// map.geoObjects.add(soligorskiyPlacemark9);
		// map.geoObjects.add(soligorskiyPlacemark10);
		// map.geoObjects.add(soligorskiyPlacemark11);
		// map.geoObjects.add(soligorskiyPlacemark12);
		// map.geoObjects.add(soligorskiyPlacemark13);
		// map.geoObjects.add(soligorskiyPlacemark14);
		// map.geoObjects.add(soligorskiyPlacemark15);
		// map.geoObjects.add(soligorskiyPlacemark16);
		// map.geoObjects.add(soligorskiyPlacemark17);
		// map.geoObjects.add(soligorskiyPlacemark18);
		// map.geoObjects.add(soligorskiyPlacemark19);
		// map.geoObjects.add(soligorskiyPlacemark20);
		// map.geoObjects.add(soligorskiyPlacemark21);
		// map.geoObjects.add(soligorskiyPlacemark22);
		// map.geoObjects.add(soligorskiyPlacemark23);
		// map.geoObjects.add(soligorskiyPlacemark24);
		// map.geoObjects.add(soligorskiyPlacemark25);
		// map.geoObjects.add(soligorskiyPlacemark26);
		// map.geoObjects.add(soligorskiyPlacemark27);
		// map.geoObjects.add(soligorskiyPlacemark28);
		// map.geoObjects.add(soligorskiyPlacemark29);
		// map.geoObjects.add(soligorskiyPlacemark31);
		// map.geoObjects.add(soligorskiyPlacemark32);
		// map.geoObjects.add(soligorskiyPlacemark33);
		// map.geoObjects.add(soligorskiyPlacemark34);
		// map.geoObjects.add(soligorskiyPlacemark35);
		// map.geoObjects.add(soligorskiyPlacemark36);
		// map.geoObjects.add(soligorskiyPlacemark37);
		// map.geoObjects.add(soligorskiyPlacemark38);
		// map.geoObjects.add(soligorskiyPlacemark39);
		// map.geoObjects.add(soligorskiyPlacemark40);
		// map.geoObjects.add(soligorskiyPlacemark41);
		// map.geoObjects.add(soligorskiyPlacemark42);
		// map.geoObjects.add(soligorskiyPlacemark43);
		// map.geoObjects.add(soligorskiyPlacemark45);
		// map.geoObjects.add(soligorskiyPlacemark46);
		// map.geoObjects.add(soligorskiyPlacemark47);
		// map.geoObjects.add(pukhovichskiyPlacemark1);
		// map.geoObjects.add(pukhovichskiyPlacemark2);
		// map.geoObjects.add(pukhovichskiyPlacemark3);
		// map.geoObjects.add(pukhovichskiyPlacemark4);
		// map.geoObjects.add(pukhovichskiyPlacemark5);
		// map.geoObjects.add(pukhovichskiyPlacemark6);
		// map.geoObjects.add(pukhovichskiyPlacemark7);
		// map.geoObjects.add(pukhovichskiyPlacemark8);
		// map.geoObjects.add(pukhovichskiyPlacemark9);
		// map.geoObjects.add(pukhovichskiyPlacemark10);
		// map.geoObjects.add(pukhovichskiyPlacemark11);
		// map.geoObjects.add(pukhovichskiyPlacemark12);
		// map.geoObjects.add(pukhovichskiyPlacemark13);
		// map.geoObjects.add(pukhovichskiyPlacemark14);
		// map.geoObjects.add(pukhovichskiyPlacemark15);
		// map.geoObjects.add(pukhovichskiyPlacemark16);
		// map.geoObjects.add(pukhovichskiyPlacemark17);
		// map.geoObjects.add(pukhovichskiyPlacemark18);
		// map.geoObjects.add(pukhovichskiyPlacemark19);
		// map.geoObjects.add(pukhovichskiyPlacemark20);
		// map.geoObjects.add(pukhovichskiyPlacemark21);
		// map.geoObjects.add(pukhovichskiyPlacemark22);
		// map.geoObjects.add(pukhovichskiyPlacemark23);
		// map.geoObjects.add(pukhovichskiyPlacemark24);
		// map.geoObjects.add(pukhovichskiyPlacemark25);
		// map.geoObjects.add(pukhovichskiyPlacemark26);
		// map.geoObjects.add(pukhovichskiyPlacemark27);
		// map.geoObjects.add(pukhovichskiyPlacemark28);
		// map.geoObjects.add(pukhovichskiyPlacemark29);
		// map.geoObjects.add(slutskiyPlacemark1);
		// map.geoObjects.add(slutskiyPlacemark2);
		// map.geoObjects.add(slutskiyPlacemark3);
		// map.geoObjects.add(slutskiyPlacemark4);
		// map.geoObjects.add(slutskiyPlacemark5);
		// map.geoObjects.add(slutskiyPlacemark6);
		// map.geoObjects.add(slutskiyPlacemark7);
		// map.geoObjects.add(slutskiyPlacemark8);
		// map.geoObjects.add(slutskiyPlacemark9);
		// map.geoObjects.add(slutskiyPlacemark10);
		// map.geoObjects.add(slutskiyPlacemark11);
		// map.geoObjects.add(slutskiyPlacemark12);
		// map.geoObjects.add(slutskiyPlacemark13);
		// map.geoObjects.add(slutskiyPlacemark14);
		// map.geoObjects.add(slutskiyPlacemark15);
		// map.geoObjects.add(slutskiyPlacemark16);
		// map.geoObjects.add(slutskiyPlacemark17);
		// map.geoObjects.add(slutskiyPlacemark18);
		// map.geoObjects.add(slutskiyPlacemark19);
		// map.geoObjects.add(slutskiyPlacemark20);
		// map.geoObjects.add(slutskiyPlacemark21);
		// map.geoObjects.add(slutskiyPlacemark22);
		// map.geoObjects.add(slutskiyPlacemark23);
		// map.geoObjects.add(slutskiyPlacemark24);
		// map.geoObjects.add(slutskiyPlacemark25);
		// map.geoObjects.add(slutskiyPlacemark26);
		// map.geoObjects.add(slutskiyPlacemark27);
		// map.geoObjects.add(slutskiyPlacemark28);
		// map.geoObjects.add(slutskiyPlacemark29);
		// map.geoObjects.add(slutskiyPlacemark30);
		// map.geoObjects.add(slutskiyPlacemark31);
		// map.geoObjects.add(slutskiyPlacemark32);
		// map.geoObjects.add(slutskiyPlacemark33);
		// map.geoObjects.add(slutskiyPlacemark34);
		// map.geoObjects.add(slutskiyPlacemark35);
		// map.geoObjects.add(slutskiyPlacemark36);
		// map.geoObjects.add(slutskiyPlacemark37);
		// map.geoObjects.add(slutskiyPlacemark38);
		// map.geoObjects.add(slutskiyPlacemark39);
		// map.geoObjects.add(slutskiyPlacemark40);
		// map.geoObjects.add(slutskiyPlacemark41);
		// map.geoObjects.add(slutskiyPlacemark42);
		// map.geoObjects.add(slutskiyPlacemark43);
		// map.geoObjects.add(slutskiyPlacemark44);
		// map.geoObjects.add(smolevichskiyPlacemark1);
		// map.geoObjects.add(smolevichskiyPlacemark2);
		// map.geoObjects.add(smolevichskiyPlacemark3);
		// map.geoObjects.add(smolevichskiyPlacemark4);
		// map.geoObjects.add(smolevichskiyPlacemark5);
		// map.geoObjects.add(smolevichskiyPlacemark6);
		// map.geoObjects.add(smolevichskiyPlacemark7);
		// map.geoObjects.add(smolevichskiyPlacemark8);
		// map.geoObjects.add(smolevichskiyPlacemark9);
		// map.geoObjects.add(smolevichskiyPlacemark10);
		// map.geoObjects.add(smolevichskiyPlacemark11);
		// map.geoObjects.add(smolevichskiyPlacemark12);
		// map.geoObjects.add(smolevichskiyPlacemark13);
		// map.geoObjects.add(smolevichskiyPlacemark14);
		// map.geoObjects.add(smolevichskiyPlacemark15);
		// map.geoObjects.add(smolevichskiyPlacemark16);
		// map.geoObjects.add(smolevichskiyPlacemark17);
		// map.geoObjects.add(smolevichskiyPlacemark18);
		// map.geoObjects.add(smolevichskiyPlacemark19);
		// map.geoObjects.add(smolevichskiyPlacemark20);
		// map.geoObjects.add(smolevichskiyPlacemark21);
		// map.geoObjects.add(smolevichskiyPlacemark22);
		// map.geoObjects.add(smolevichskiyPlacemark23);
		// map.geoObjects.add(smolevichskiyPlacemark24);
		// map.geoObjects.add(smolevichskiyPlacemark25);
		// map.geoObjects.add(smolevichskiyPlacemark26);
		// map.geoObjects.add(nesvizhskiyPlacemark1);
		// map.geoObjects.add(nesvizhskiyPlacemark2);
		// map.geoObjects.add(nesvizhskiyPlacemark3);
		// map.geoObjects.add(nesvizhskiyPlacemark4);
		// map.geoObjects.add(nesvizhskiyPlacemark5);
		// map.geoObjects.add(nesvizhskiyPlacemark6);
		// map.geoObjects.add(nesvizhskiyPlacemark7);
		// map.geoObjects.add(nesvizhskiyPlacemark8);
		// map.geoObjects.add(nesvizhskiyPlacemark9);
		// map.geoObjects.add(nesvizhskiyPlacemark10);
		// map.geoObjects.add(nesvizhskiyPlacemark11);
		// map.geoObjects.add(nesvizhskiyPlacemark12);
		// map.geoObjects.add(nesvizhskiyPlacemark13);
		// map.geoObjects.add(nesvizhskiyPlacemark14);
		// map.geoObjects.add(nesvizhskiyPlacemark15);
		// map.geoObjects.add(nesvizhskiyPlacemark16);
		// map.geoObjects.add(nesvizhskiyPlacemark17);
		// map.geoObjects.add(nesvizhskiyPlacemark18);
		// map.geoObjects.add(nesvizhskiyPlacemark19);
		// map.geoObjects.add(nesvizhskiyPlacemark20);
		// map.geoObjects.add(nesvizhskiyPlacemark21);
		// map.geoObjects.add(nesvizhskiyPlacemark22);
		// map.geoObjects.add(nesvizhskiyPlacemark23);
		// map.geoObjects.add(starodorozhskiyPlacemark1);
		// map.geoObjects.add(starodorozhskiyPlacemark2);
		// map.geoObjects.add(starodorozhskiyPlacemark3);
		// map.geoObjects.add(starodorozhskiyPlacemark4);
		// map.geoObjects.add(starodorozhskiyPlacemark5);
		// map.geoObjects.add(starodorozhskiyPlacemark6);
		// map.geoObjects.add(starodorozhskiyPlacemark7);
		// map.geoObjects.add(starodorozhskiyPlacemark8);
		// map.geoObjects.add(starodorozhskiyPlacemark9);
		// map.geoObjects.add(starodorozhskiyPlacemark10);
		// map.geoObjects.add(starodorozhskiyPlacemark12);
		// map.geoObjects.add(starodorozhskiyPlacemark13);
		// map.geoObjects.add(starodorozhskiyPlacemark14);
		// map.geoObjects.add(starodorozhskiyPlacemark15);
		// map.geoObjects.add(starodorozhskiyPlacemark16);
		// map.geoObjects.add(starodorozhskiyPlacemark17);
		// map.geoObjects.add(stolbcovskiyPlacemark1);
		// map.geoObjects.add(stolbcovskiyPlacemark2);
		// map.geoObjects.add(stolbcovskiyPlacemark3);
		// map.geoObjects.add(stolbcovskiyPlacemark4);
		// map.geoObjects.add(stolbcovskiyPlacemark5);
		// map.geoObjects.add(stolbcovskiyPlacemark6);
		// map.geoObjects.add(stolbcovskiyPlacemark7);
		// map.geoObjects.add(stolbcovskiyPlacemark8);
		// map.geoObjects.add(stolbcovskiyPlacemark9);
		// map.geoObjects.add(stolbcovskiyPlacemark10);
		// map.geoObjects.add(stolbcovskiyPlacemark11);
		// map.geoObjects.add(stolbcovskiyPlacemark12);
		// map.geoObjects.add(stolbcovskiyPlacemark13);
		// map.geoObjects.add(stolbcovskiyPlacemark14);
		// map.geoObjects.add(stolbcovskiyPlacemark15);
		// map.geoObjects.add(stolbcovskiyPlacemark16);
		// map.geoObjects.add(stolbcovskiyPlacemark17);
		// map.geoObjects.add(stolbcovskiyPlacemark18);
		// map.geoObjects.add(stolbcovskiyPlacemark19);
		// map.geoObjects.add(stolbcovskiyPlacemark20);
		// map.geoObjects.add(stolbcovskiyPlacemark21);
		// map.geoObjects.add(stolbcovskiyPlacemark22);
		// map.geoObjects.add(stolbcovskiyPlacemark23);
		// map.geoObjects.add(stolbcovskiyPlacemark24);
		// map.geoObjects.add(stolbcovskiyPlacemark25);
		// map.geoObjects.add(stolbcovskiyPlacemark26);
		// map.geoObjects.add(stolbcovskiyPlacemark27);
		// map.geoObjects.add(uzdenskiyPlacemark1);
		// map.geoObjects.add(uzdenskiyPlacemark2);
		// map.geoObjects.add(uzdenskiyPlacemark3);
		// map.geoObjects.add(uzdenskiyPlacemark4);
		// map.geoObjects.add(uzdenskiyPlacemark5);
		// map.geoObjects.add(uzdenskiyPlacemark6);
		// map.geoObjects.add(uzdenskiyPlacemark7);
		// map.geoObjects.add(uzdenskiyPlacemark8);
		// map.geoObjects.add(uzdenskiyPlacemark9);
		// map.geoObjects.add(uzdenskiyPlacemark10);
		// map.geoObjects.add(uzdenskiyPlacemark11);
		// map.geoObjects.add(uzdenskiyPlacemark12);
		// map.geoObjects.add(uzdenskiyPlacemark13);
		// map.geoObjects.add(uzdenskiyPlacemark14);
		// map.geoObjects.add(uzdenskiyPlacemark15);
		// map.geoObjects.add(uzdenskiyPlacemark16);
		// map.geoObjects.add(chervenskiyPlacemark1);
		// map.geoObjects.add(chervenskiyPlacemark2);
		// map.geoObjects.add(chervenskiyPlacemark3);
		// map.geoObjects.add(chervenskiyPlacemark4);
		// map.geoObjects.add(chervenskiyPlacemark5);
		// map.geoObjects.add(chervenskiyPlacemark6);
		// map.geoObjects.add(chervenskiyPlacemark7);
		// map.geoObjects.add(chervenskiyPlacemark8);
		// map.geoObjects.add(chervenskiyPlacemark9);
		// map.geoObjects.add(chervenskiyPlacemark10);
		// map.geoObjects.add(chervenskiyPlacemark11);
		// map.geoObjects.add(chervenskiyPlacemark12);
		// map.geoObjects.add(chervenskiyPlacemark13);
		// map.geoObjects.add(chervenskiyPlacemark14);
		// map.geoObjects.add(chervenskiyPlacemark15);
		// map.geoObjects.add(chervenskiyPlacemark16);
		// map.geoObjects.add(chervenskiyPlacemark17);
		// map.geoObjects.add(chervenskiyPlacemark18);
		// map.geoObjects.add(chervenskiyPlacemark19);

		//Resetberezinskiy();
		// EventsResetSchoolsborisovsky();
		// EventsResetSchoolschervenskiy();
		// EventsResetSchoolsdzerzhinskiy()
		// EventsResetSchoolsjodino();
		// EventsResetSchoolskletskiy();
		// EventsResetSchoolskopilskiy();
		// EventsResetSchoolskrupski();
		// EventsResetSchoolslogoyski();
		// EventsResetSchoolslubanski();
		// EventsResetSchoolsminskiy();
		// EventsResetSchoolsmolodzechnenskiy();
		// EventsResetSchoolsmyadzelskiy();
		// EventsResetSchoolsnesvizhskiy();
		// EventsResetSchoolspukhovichskiy();
		// EventsResetSchoolsslutskiy();
		// EventsResetSchoolssmolevichskiy();
		// EventsResetSchoolssoligorskiy();
		// EventsResetSchoolsstarodorozhskiy();
		// EventsResetSchoolsstolbcovskiy();
		// EventsResetSchoolsuzdenskiy();
		// EventsResetSchoolsvileyskiy();
		// EventsResetSchoolsvolozhinskiy();
	});
}